urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    (r'^clinamen/images/([A-Za-z]+)', 'clinamen.filelist.views.imagelist'),
    (r'^clinamen/runlogs/([A-Za-z]+)', 'clinamen.filelist.views.runloglist'),
    
    (r'^clinamen/filters/([A-Za-z]+)', 'clinamen.filelist.views.filteredlist'),
    (r'^clinamen/zipfile/([A-Za-z]+)', 'clinamen.filelist.views.filteredzip'),
    (r'^clinamen/dayseq/([A-Za-z]+)', 'clinamen.filelist.views.dayseqview'),
    (r'^dayseq', 'clinamen.filelist.views.dayseqview'),
    
    (r'^clinamen/imgproc/methodlist', 'clinamen.filelist.views.methodlist'),
    (r'^clinamen/imgproc/remove', 'clinamen.filelist.views.removemethod'),
    (r'^clinamen/imgproc/add', 'clinamen.filelist.views.addmethod'),
    (r'^clinamen/imgproc/edit', 'clinamen.filelist.views.editparams'),
    (r'^clinamen/imgproc/update', 'clinamen.filelist.views.updateparams'),
    (r'^clinamen/imgproc/process', 'clinamen.filelist.views.processtype'),    
    
    (r'^clinamen/imgproc/countsample', 'clinamen.filelist.views.countsample'),
    (r'^clinamen/imgproc/getsample', 'clinamen.filelist.views.getsample'),
    (r'^clinamen/imgproc/setsample', 'clinamen.filelist.views.setsample'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'static'}),
)

filelist/models.py
import os
import numpy as np
import re
import inspect
import collections
from scipy.misc import toimage
from odysseus.imageio import imgimport_intelligent, list_of_frames
os.environ['DJANGO_SETTINGS_MODULE'] = "settings"
from django.db import models
from PIL import Image
import filelist.filesettings as filesettings

class RunLogInfo(models.Model):
	#path = models.FilePathField(filesettings.RL_DIR, primary_key=True)
	path = models.CharField(max_length=200, primary_key=True)
	loc_key = models.CharField(max_length=100)
	time = models.DateTimeField()
	sequencepath = models.CharField(max_length=200)
	listiterationnumber = models.IntegerField(null=True, blank=True)
	liststarttime = models.DateTimeField(null=True,blank=True)
	sequenceduration = models.FloatField(null=True,blank=True)
	description = models.TextField(null=True, blank=True)
	exceptions = models.TextField(null=True, blank=True)
	class Meta:
		ordering=['-time']
		
class VariableValue(models.Model):
	name = models.CharField(max_length=30)
	value = models.FloatField()
	runlog = models.ForeignKey('RunLogInfo')

class ImageInfo(models.Model):
	#path = models.FilePathField(filesettings.IMG_DIR, primary_key=True)
	path = models.CharField(max_length=100, primary_key=True)
	loc_key = models.CharField(max_length=100, null=True, blank=True)
	time = models.DateTimeField(null=True, blank=True)
	height = models.IntegerField(null=True, blank=True)
	width = models.IntegerField(null=True, blank=True)
	number_of_frames = models.IntegerField(null=True, blank=True)
	imgtype = models.ForeignKey('ImageType', null=True, blank=True)
	runlog = models.ForeignKey('RunLogInfo', null=True, blank=True)	
	def makeRawFrames(self):
		frames = np.dstack(list_of_frames(self.path))
		
		self.width = np.size(frames,0)
		self.height = np.size(frames,1)	
		self.number_of_frames = np.size(frames,2)
				
		for ii in range(np.size(frames,2)):
			filename = os.path.splitext(os.path.split(self.path)[1])[0]+'_'+str(ii)+'.png'
			
			newframe = RawFrame(sourceimage=self, framenumber=ii)
			newframe.saveframe(frames[:,:,ii], filename)
			newframe.save()
	def deleteProcFrames(self):
		ProcessedFrame.objects.filter(sourceimage=self).delete()
	def ProcessImage(self): 
		if self.imgtype:
			for method in self.imgtype.methods.all():
				procmodule = __import__(method.modulename)
				reload(procmodule)
				procmethod = getattr(procmodule, method.name)
				argdict = {}
				for param in TypeParameters.objects.filter(imagetype=self.imgtype, methodargument__method=method):
					argdict[param.methodargument.name]=param.value
				for ROIparam in TypeROI.objects.filter(imagetype=self.imgtype, methodargument__method=method):
					argdict[ROIParam.methodargument.name]=ROIparam.ToDict()
				try:
					result=procmethod(self.path, **argdict)
					if not isinstance(result,tuple):
						result = (result,)
					for ii in range(len(result)):
						if isarray(result[ii]):
							filename=os.path.splitext(os.path.split(self.path)[1])[0]+'_'+method.name+'_'+str(ii)+'.png'						
							newrecord = ProcessedFrame(sourceimage=self, method=method, framenumber=ii) 
							newrecord.saveframe(result[ii], filename, cmin=0, cmax=1)
							newrecord.save()
						else:
							newrecord = ProcessedValue(sourceimage=self, method=method, value=float(item[ii]), index=ii)
							newrecord.save()
				except: 
					pass
	def getClosestSequence(self):
		sql = "SELECT * FROM filelist_runloginfo ORDER BY ABS(TIMESTAMPDIFF(SECOND, time,'" + self.time.strftime('%Y-%m-%d %H:%M:%S') + "')-sequenceduration) LIMIT 1"
		for retrunlog in RunLogInfo.objects.raw(sql):
			self.runlog = retrunlog
			self.getTypeFromDescription()
	def getTypeFromDescription(self): 
		matchObj = re.search("imgtype=(\w+)", self.runlog.description)
		if matchObj:
			(self.imgtype, created)=ImageType.objects.get_or_create(name=matchObj.group(1))
	class Meta:
		ordering=['-time']

class FrameInfo(models.Model):
	pngpath = models.CharField(max_length=100, primary_key=True)
	pngurl = models.CharField(max_length=100)
	pngheight = models.IntegerField()
	pngwidth = models.IntegerField()
	thumbpath = models.CharField(max_length=100)
	thumburl = models.CharField(max_length=100)	
	thumbheight = models.IntegerField()
	thumbwidth = models.IntegerField()
	framenumber = models.IntegerField(null=True, blank=True)
	sourceimage = models.ForeignKey('ImageInfo', null=True, blank=True)	
	def saveframe(self, frame, filename, cmin=None, cmax=None):
		self.pngpath=os.path.join(filesettings.PNG_DIR,filename)
		self.pngurl=filesettings.PNG_URL+filename
		self.thumbpath=os.path.join(filesettings.THUMB_DIR,filename)
		self.thumburl=filesettings.THUMB_URL+filename		
		
		im=toimage(frame, cmin=cmin, cmax=cmax)
		im.save(self.pngpath)
			
		self.pngwidth = np.size(frame,0)
		self.pngheight = np.size(frame,1)			
		aspect=float(self.pngwidth)/float(self.pngheight)
		
		if aspect>1:
			self.thumbwidth = filesettings.THUMB_SIZE
			self.thumbheight = int(filesettings.THUMB_SIZE/aspect)
		else:
			self.thumbwidth = int(filesettings.THUMB_SIZE * aspect)
			self.thumbheight = filesettings.THUMB_SIZE
		im.thumbnail([self.thumbwidth, self.thumbheight], Image.ANTIALIAS) 		
		im.save(self.thumbpath)				
	class Meta:
		abstract=True
		ordering=['framenumber']
	
class ProcessingMethod(models.Model):
	modulename = models.CharField(max_length=100)
	name = models.CharField(max_length=30) 
	def getargs(self):
		procmodule = __import__(self.modulename)
		#procmethod = procmodule.getAttr(procmodule, self.name)
		procmethod = getattr(procmodule, self.name)
		argspec = inspect.getargspec(procmethod)
		for keyword in argspec.args[1:]:
			newmetharg, created = MethodArgument.objects.get_or_create(method=self, name=keyword)
			if re.search("roi_(\w+)", keyword):
				newmetharg.isROI = True
			newmetharg.save()
	class Meta:
		unique_together = ("modulename", "name")
	
class MethodArgument(models.Model):
	method = models.ForeignKey('ProcessingMethod')
	name = models.CharField(max_length=30)	
	isROI = models.NullBooleanField(null=True, blank=True)

class ImageType(models.Model):
	name = models.CharField(max_length=30, primary_key=True)
	methods = models.ManyToManyField('ProcessingMethod')
	parameters = models.ManyToManyField('MethodArgument', through='TypeParameters')	
	sample = models.ForeignKey('RawFrame', null=True, blank=True)
	def ClearProcessed(self):
		ProcessedFrame.objects.filter(sourceimage__imgtype=self).delete()
	def ProcessType(self):
		#imtype = ImageType.objects.get(name=self.name)
		#for iminfo in imtype.ImageInfo_set.all():
		for iminfo in self.imageinfo_set.all():
			iminfo.ProcessImage()
	
class TypeParameters(models.Model):
	imagetype = models.ForeignKey('ImageType')
	methodargument = models.ForeignKey('MethodArgument')
	value = models.FloatField()	
	class Meta:
		unique_together = ("imagetype", "methodargument")
		
class TypeROI(models.Model):
	imagetype = models.ForeignKey('ImageType')
	methodargument = models.ForeignKey('MethodArgument')
	x1 = models.IntegerField(null=True, blank=True)
	x2 = models.IntegerField(null=True, blank=True)
	y1 = models.IntegerField(null=True, blank=True)
	y2 = models.IntegerField(null=True, blank=True)
	def ToDict(self):
		return {"x1": x1, "x2": x2, "y1": y1, "y2": y2}
	class Meta:
		unique_together = ("imagetype", "methodargument")

class ProcessedFrame(FrameInfo):
	method = models.ForeignKey('ProcessingMethod', null=True, blank=True)
	
class RawFrame(FrameInfo):
	class Meta:
		abstract=False
	
class ProcessedValue(models.Model):
	sourceimage = models.ForeignKey('ImageInfo')
	method = models.ForeignKey('ProcessingMethod', null=True, blank=True)
	value = models.FloatField()
	index = models.IntegerField(null=True, blank=True)
	class Meta:
		unique_together = ("sourceimage", "method")

def get_iterable(x):
	if isinstance(x, collections.Iterable):
		return x
	else:
		return (x,)

def isarray(s):
	try:
		len(s)
		return True
	except TypeError:
		return False
	
	

templates/dayseq.html
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>
	
<link rel="stylesheet" href="../css/jquery.treeview.css" />
<link rel="stylesheet" href="../css/screen.css" />
	
<script src="../js/jquery.js" type="text/javascript"></script>
<script src="../js/jquery.cookie.js" type="text/javascript"></script>
<script src="../js/jquery.treeview.js" type="text/javascript"></script>
	
<script type="text/javascript" src="../demo.js"></script>
	
</head>
<body>
{% load pagination_tags %}
{% autopaginate runlog_list 500 %}
{% paginate %}
<div id="main">

templates/imglist.html
<table border=1>
<tr>
<th>Image time
<th>Processed frames
<th>Raw frames
</tr>
{% for imginfo in img_list %}
<tr>
<td>{{imginfo.time|date:"M-d-Y H:i:s"}}
<td>
{% for thumbinfo in imginfo.thumbinfo_set.all %}
{% if thumbinfo.framenumber < 0 %}
<img src="{{thumbinfo.url}}" height=64 width=64>
{% endif %}
{% endfor %}  
<td>
{% for thumbinfo in imginfo.thumbinfo_set.all %}
{% if thumbinfo.framenumber >= 0 %}
<img src="{{thumbinfo.url}}" height=64 width=64>
{% endif %}
{% endfor %}  
</tr>
{% endfor %}
</table>

templates/methodlist.html
<div id="activetype" data-activetype={{activetype.name}}><b>Image type:</b> {{activetype.name}}</div>

<p>Add a processing method: 
<select id="methodlist">
	{% for method in method_list %}
		<option data-modulename="{{method.modulename}}" data-methodname="{{method.name}}" value="{{method.modulename}}___{{method.name}}">{{method.modulename}}::{{method.name}}</option>
	{% endfor %}
</select>	
</p>
<p><input type="button" name="addmethod" id="addmethod" value="Add this method"></p>

<p>Active methods:</p>
{% for method in active_list %}
<p><b>Module name:</b> {{method.modulename}} <b>Function name:</b> {{method.name}} <input type="button" name="edit" data-modulename="{{method.modulename}}" data-methodname="{{method.name}}" value="Edit Parameters"><input type="button" name="remove" data-modulename="{{method.modulename}}" data-methodname="{{method.name}}" value="Remove method"></p>
{% endfor %}

<p><input type="button" name="processtype" id="processtype" value="Process this type"></p>

templates/paramlist.html
<div id="activemethod" data-modulename={{activemethod.modulename}} data-methodname={{activemethod.name}}><b>Parameters for method:</b> {{activemethod.modulename}}.{{activemethod.name}}</div>

{% for arg, value in arg_params.items %}
<p>{{arg}}: <input type="text" name={{arg}} value={{value}}> 
{% endfor %}

{% for arg, value in arg_rois.items %}
<p>{{arg}}: <img name="roi" data-arg="{{arg}}" data-roi="{{value}}" src={{sampleframe.pngurl}}> 
{% endfor %}

<p><input type="button" id="update" value="Update Values" name="update"></p>

templates/runloglist.html
{% load pagination_tags %}
{% autopaginate runlog_list %}
{% paginate %}
<table border=1>
<tr>
<th>Run time
<th>Sequence path
<th>Duration
<th>Description
<th>Variables
<th>Image time
<th>Image type
<th>Raw frames
<th>Processed frames
</tr>
{% for runloginfo in runlog_list %}
<tr>
<td>{{runloginfo.time|date:"M-d-Y H:i:s"}}
<td>{{runloginfo.shortpath}}
<td>{{runloginfo.sequenceduration}}
<td>{{runloginfo.description}}
<td>
{% for varvalue in runloginfo.variablevalue_set.all %}
{{varvalue.name}} = {{varvalue.value}} <BR>
{% endfor %}
<td>
{% for imginfo in runloginfo.imageinfo_set.all|slice:":2" %}
{{imginfo.time|date:"M-d-Y H:i:s"}}<BR>
{% endfor %}  
<td>
{% for imginfo in runloginfo.imageinfo_set.all|slice:":2" %}
{{imginfo.imgtype.name}}<BR>
{% endfor %}  
<td>
{% for imginfo in runloginfo.imageinfo_set.all|slice:":2" %}
{% for frameinfo in imginfo.rawframe_set.all %}
<a href="{{frameinfo.pngurl}}"><img src="{{frameinfo.thumburl}}" height=64 width=64></a>
{% endfor %}
<BR>
{% endfor %}  
<td>
{% for imginfo in runloginfo.imageinfo_set.all|slice:":2" %}
{% for frameinfo in imginfo.processedframe_set.all %}
<a href="{{frameinfo.pngurl}}"><img src="{{frameinfo.thumburl}}" height=64 width=64></a>
{% endfor %}
<BR>
{% endfor %}  
</tr>
{% endfor %}
</table>

templates/sampleimages.html
{% for frameinfo in sampleimage.rawframe_set.all %}
<img name="sample" src="{{frameinfo.pngurl}}">
{% endfor %}